[package]
name = "bevy_framepace"
version = "0.9.1"
edition = "2021"
resolver = "2"
description = "Frame pacing and frame limiting for Bevy"
license = "MIT OR Apache-2.0"
repository = "https://github.com/aevyrie/bevy_framepace"
documentation = "https://docs.rs/bevy_framepace"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { version = "0.9", default-features = false, features = [
    "bevy_render",
    "bevy_winit",
] }
wasm_thread = "0.2"

[features]
default = ["x11"]
x11 = ["bevy/x11"]

[dev-dependencies]
bevy_mod_picking = "0.10"
bevy = { version = "0.9", default-features = false, features = [
    "bevy_ui",
    "bevy_text",
    "bevy_core_pipeline",
    "bevy_winit",
] }
