[package]
name = "bevy_framepace"
version = "0.3.0"
edition = "2021"
resolver = "2"
description = "Frame pacing and frame limiting for Bevy"
license = "MIT OR Apache-2.0"
repository = "https://github.com/aevyrie/bevy_framepace"
documentation = "https://docs.rs/bevy_framepace"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false, features = [
    "bevy_winit",
    "render",
    "x11",
] }
spin_sleep = "1.0"

[dev-dependencies]
bevy_mod_picking = { git = "https://github.com/aevyrie/bevy_mod_picking", branch = "main" }
