[package]
name = "bevy_framepace"
version = "0.5.0"
edition = "2021"
resolver = "2"
description = "Frame pacing and frame limiting for Bevy"
license = "MIT OR Apache-2.0"
repository = "https://github.com/aevyrie/bevy_framepace"
documentation = "https://docs.rs/bevy_framepace"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false, features = [
    "bevy_render",
    "bevy_winit",
] }

[features]
default = ["x11"]
x11 = ["bevy/x11"]

[dev-dependencies]
bevy_mod_picking = { git = "https://github.com/aevyrie/bevy_mod_picking", branch = "main" }
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false, features = [
    "bevy_ui",
    "bevy_text",
    "bevy_core_pipeline",
] }
